### ISSUE TITLE
Steriods item does not permanently increase carry weight allowance

### ISSUE THREAD

**Issue by zexlr8er** [zexlr8er/Wazzal_II#13]
'Steroids' item appears to temporarily apply additional carry weight, but this disappears after switching to Wolf IV then returning to Captain, or revisiting then returning from a store. To replicate: 

1) Leave the bridge of the Wolf IV ("B")
2) Press "I" to verify max weight allowance is 120
3) Visit store by right clicking
4)  Purchase "steroids" item, and leave store
5) Press "I" and verify max weight allowance is 150
6) Revisit store and leave
7) Press "I", and observe max weight allowance incorrectly returned to 120

This may be something I'm doing wrong on the modding side of things that prevents the increase in max weight from being applied permanently, but if not this may be a Notrium bug associated with changing inventories.

Behind the scenes: To purchase 'steroids', player must first visit a 'store'. This plot object causes the player to swap race (to 'store') and temporarily swap to the store's own inventory. To prevent increase in max weight allowance from being applied to the store's inventory, the 'steroids' item (item 155) doesn't apply the max weight allowance change itself but instead calls a script (script 111) which runs after the player returns to being the Captain, thus theoretically applying a 30 point max weight allowance to the Captain's inventory.

**Comment by villemonkkonen** [comment]
Notrium was resetting it to the race default. Now it's adding up the bonuses to the current races carry amount. It also results in the shops being able to carry more when using steroids, but that probably doesn't matter.

**Comment by zexlr8er** [comment]
Thanks @villemonkkonen. Fixed in latest Steam version of Notrium.
