### ISSUE TITLE
Screen shakes and player loses control of creature when crossing wrapped boundary when carried

### ISSUE THREAD

**Issue by zexlr8er** [zexlr8er/Wazzal_II#22]
Player can control and be carried by Confederate Destroyers by pressing "C" when near the creature. When attempting to cross a wrapped/reflected boundary, screen shakes as creature attempts and fails to cross boundary. When screen regains normal behavior, player can no longer control creature, and sometimes cannot be un-carried by pressing "C" again.

To replicate, enter Enkommono system (first jumpgate from first system). Take control of ship Crego, and attempt to move through any wrapped (green) boundary). 

This occurs despite the creature ("23;//Confed destroyer") being set to: _"1;//creature can move from area to another"_

**Comment by zexlr8er** [comment]
Hi @villemonkkonen, this is an interesting one that just popped up. Let me know if you can replicate!

**Comment by villemonkkonen** [comment]
Found the error and releasing a fix right now. Hadn't tested vehicles with wrapped maps before now.

**Comment by zexlr8er** [comment]
Fixed perfectly by @villemonkkonen in latest Steam update.
