### ISSUE TITLE
Using wood to create fire results in black screen

### ISSUE THREAD

**Issue by zexlr8er** [zexlr8er/Wazzal_II#3]
Occurs when lighting fire with wood item. To replicate: 

1) Use the editor to add one of these "wood" items to the Wolf IV's bridge
2) Test lighting a fire there.

**Comment by villemonkkonen** [comment]
It was a divide by zero in the physics engine.

**Comment by zexlr8er** [comment]
Fixed by @villemonkkonen in latest Steam version of Notrium.
