### ISSUE TITLE
Kinmegag substations

### ISSUE THREAD

**Issue by Infernus444** [zexlr8er/Wazzal_II#30]
Finding all 10 substations is extremely frustrating as you need to check under every single tree, since they are displayed under them. Spawning more substations (12 spawned, still requires 10) could rise the chances of spotting them easier. 

I spent an hour checking every tree and I still couldn't find the last one.

**Comment by zexlr8er** [comment]
Absolutely, I will put in a fix for this.

**Comment by robbibt** [comment]
Looks like I already made an attempt to fix this; it may need to be exaggerated even more. https://github.com/zexlr8er/Wazzal_II/commit/5d77ea94fe5edc9956be592c7ae5755dab98a629

**Comment by robbibt** [comment]
(Fixed by increasing substation count to 14 - four above minimum. Still challenging despite this!)
