### ISSUE TITLE
Issues with sound

### ISSUE THREAD

**Issue by zexlr8er** [zexlr8er/Wazzal_II#32]
Several issues with sound in Wazzal II:

1) When playing the mod after using the map editor, all ingame sounds except music do not work (e.g. weapons, ambient sounds, plot objects). Getting sounds to play again requires Notrium is exited and re-opened. EDIT: This also occurs if you play a mod, die or exit it, and then relaunch the mod.

2) Certain sounds (just plot objects?) do not play. Several ways to replicate: use any jumpgate, which should play "jumpgate.wav" when used by player. No sound will play, despite this file being located correctly in the "sound/Wazzal II" directory. Also visit Wolf IV bridge (press B), and use any fuel, health or energy pump/pool (will need to have low health/energy). No sounds will play, despite being set to play "electric2.wav"/"oiler.wav"/"hum.wav" when used. Try overheating/overcooling: no "hot.wav" or "cold.wav" will play.

3) This a weird one. The player can be carried by a "Flying fighter - stationary" ("82;//identifier") creature, which allows the player to fire the creature's primary weapon ("88;//weapon number", with sound "phaser.wav"). This weapon sound works unless the following code is added to the "day_sounds" block of the "Meadow" climate type ("14;//identifier"):

```
birds4.wav;
birds5.wav;
```

Best way to replicate this is to use the editor to add a "Flying fighter - stationary" ("82;//identifier") to the Wolf IV's bridge, control the creature by pressing "X" when near, and then attempt to fire primary weapon. You should hear the sound when the above code is not added to the  "Meadow" climate type ("14;//identifier") "day_sounds" block, and not hear sounds if it is.

**Comment by zexlr8er** [comment]
Another one for you, @villemonkkonen. I don't think any of these were a problem until recently, and I haven't worked out the logic of what sounds work and what ones don't.

**Comment by villemonkkonen** [comment]
Looks like Notrium has reserved space for just 200 samples, and after that is full it outright doesn't work. That would explain why on the first try some samples don't work, and after the 200 is reached, it doesn't even find the old ones. I'm working on making it sensible.

**Comment by villemonkkonen** [comment]
Now it loads up to 1000 sounds, and the previously loaded sounds work even if that limit is reached.

**Comment by zexlr8er** [comment]
Fantastic, thanks Ville. Will let you know if I have any further sound troubles.
