### ISSUE TITLE
Unpredictable bug where items in inventory become invisible

### ISSUE THREAD

**Issue by zexlr8er** [zexlr8er/Wazzal_II#5]
Often occurs after changing between ship and captain. Items in both ship and captain's inventory disappear, but are usually still accessible through hotkeys and wielding as weapons. Difficult to replicate as does not always occur, but can try:

1) As soon as game starts, press "i" to verify Wolf IV's inventory contains items
2) Press "B" to leave bridge
3) Press "i" to verify Captain's inventory contains items
4) Walk down to store, right click to open.
5) Purchase any item for Captain (i.e. bullets). Leave store
6) Press "i" for inventory. If issue has occurred, inventory should be blank or contain only one or two items
7) Return to Wolf IV's bridge (right click on control panel).
8) Press "i". If issue has occurred, inventory should be blank or contain only one or two items
9) Repeat process if issue does not occur the first time

![image](https://cloud.githubusercontent.com/assets/16367282/11969255/239fc116-a96b-11e5-9b46-65c0c5097ab8.png)

**Comment by Infernus444** [comment]
I know what the problem is:
https://github.com/verhoevenv/OpenNotrium/issues/46

**Comment by villemonkkonen** [comment]
Thanks! That's exactly what it was.

**Comment by zexlr8er** [comment]
As far as I can tell through brief testing, this has been fixed by @villemonkkonen in the latest Steam version of Notrium. Thanks for identifying the issue @Infernus444!
