### ISSUE TITLE
Overburdening effects remain even after dropping items

### ISSUE THREAD

**Issue by zexlr8er** [zexlr8er/Wazzal_II#73]
I think this may be related to changing races/inventories when overburdened. To replicate:
1. Press "B" to leave Wolf IV bridge
2. Enter testing mode by pressing "9" in-game, then press "7" to unlock all ranks and obtain additional money. Purchase 9 "MG Turret"s or any other items heavy enough to bring player over weight limit
3. Return to space ("Click to enter bridge", which changes race and inventory), then press "B" to leave bridge again
4. Drop all heavy items, and observe overburdening effects still in place

**Comment by zexlr8er** [comment]
Hi @villemonkkonen, I lied: there actually is one more of the classic old bugs that is still hanging around... and of course I would only rediscover it after releasing the final version of the mod!

**Comment by villemonkkonen** [comment]
Thanks for the excellent instructions, I was able to fix it. It was exactly as you suggested, changing the race didn't reset the overburden amount. Just released a new version to Steam.

**Comment by zexlr8er** [comment]
Thanks again; all fixed!
