### ISSUE TITLE
Sound breaks down

### ISSUE THREAD

**Issue by Infernus444** [zexlr8er/Wazzal_II#87]
On Freeware edition, only on Wazzal mode, the sound stops playing after few minutes. The music and the sounds in the main menu still works, but the ones in the game does not. Saving and loading does not fix the issue, but restarting the game does. It, however, breaks again after few minutes. It starts with few sounds at first, but extends to every type.

**Comment by zexlr8er** [comment]
This sounds like something related to #32 (Notrium only loading in a maximum amount of sounds in one go), which was theoretically fixed in the latest Steam version.
